### ISSUE TITLE
Great widget, what are your plans?

### ISSUE THREAD

**Issue by ppoetsma** [mendix/CopyURL#1]
Hi, I have been using the copy to clipboard widget (https://github.com/Luch/CopyToClipboard) for a while but it is not compatible with the latest Mx versions. Your CopyURL widget seems to be a good replacement. However, why is it a combination of an inputbox and a button and not just the button? Inputboxes are native available in all sizes and formats so no need to create one.

What are your plans with this widget? Will it be added to the appstore?

Regards,
Paul

**Comment by RoelandSalij** [comment]
Thanks Paul,
The reason is the button relying on the html structure of the widget and classes of parent elements.
Is your question a result of that this widget doesn't fit in the look and feel of your website? Can you post an example of use cases you are running in to?

You're right. This widget is production ready, we'll add it to the App Store soon. It just needs a logo :)

**Comment by ppoetsma** [comment]
Hi Roeland,

Basically, the text input that is shown is inferior to the native input
widgets. If the prefix function is a hard requirement then leave it, but
make it easy to hide the input widget or add a flag to the widget
configuration to not render it at all.

My use case is just a copy-to-clipboard button that copies data from an
attribute, which is typically visible to the user, to the clipboard. See
the screenshot below; for security reasons most of the JSON response is
obfuscated. So the label of the button is variable and there is no input
widget. The widget itself is connected to an attribute, otherwise is
does not know where to get its data from.

Additional to that, the first feature request you will get is to enhance
the widget's input to support radio buttons, check boxes, date pickers,
textarea, etc. Those widgets are native available in Mendix, therefore
my advice to make it work as a button-only kind of widget too. To
support customer date/time formatting, for example, the widget might
need to look at a CSS selector and not an attribute. Then it would be
possible to copy the text from the text widget too. That would be cool
and then is your prefix need solved as well.

See the two screenshots for my use case and widget properties.

And when the widget itself has a proper class name, not "widgetname", it
can be identified properly for styling.

Regards,
Paul

**Comment by RoelandSalij** [comment]
Sounds like nice improvements. Have to dive into this shortly.

Unfortunately the screenshots aren't visible to me... Can you give that another try?

Thanks!

**Comment by ppoetsma** [comment]
![ciejgaai](https://cloud.githubusercontent.com/assets/742198/12644279/155f80aa-c5c2-11e5-98eb-2b6365c437b8.png)
![gibcacih](https://cloud.githubusercontent.com/assets/742198/12644285/19d21152-c5c2-11e5-9e0f-2d789fa09845.png)

**Comment by ppoetsma** [comment]
Replying to Github emails with images in them skips the images. I added them manually.

**Comment by RoelandSalij** [comment]
Hi Paul, 
I've created a separate widget for this:
https://github.com/mendix/ClipboardTextCopy/releases/download/v1.0/ClipboardTextCopy.mpk
I will add this one to the App Store and it works only with elements of input type text or textarea.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

> The HTMLInputElement.select() method selects all the text in a <textarea> element or an <input> element with a text field.
